Hiram-Wong/ZyPlayer

src/lib/utils/tools.ts
UPDATE src/lib/utils/tools.ts isLiveM3U8
=> UPDATE src/lib/utils/tools.ts isLiveM3U8

src/pages/setting/base/components/DialogData.vue
Add error handler for common config import.
在导入本地json失败时提示。
=> Add error handler for import

src/renderer/src/pages/Play.vue, src/renderer/src/pages/film/Detail.vue, src/renderer/src/utils/cms.ts, src/renderer/src/utils/drpy/drpy3.ts, src/renderer/src/utils/drpy/drpyInject.ts, src/renderer/src/utils/drpy/drpy_test/test_urljoin.mjs
优化和修复
优化:第三方嗅探器链接支持传递js点击参数，农民影视3 t3源可正常嗅探
修复:urljoin被自动转义导致的问题
新增:drpy3接口:fyfilter支持fyclass变量替换
=> hipy相关源解析和播放增强

src/renderer/src/utils/drpy/drpy3.ts
=> add $js for t3

src/renderer/src/pages/setting/tool/EditSource.vue, src/renderer/src/utils/drpy/drpy_suggestions/drpy_suggestions.ts
=> 写源工具增加完整的drpy可能涉及的函数变量智能提示。

src/renderer/src/utils/drpy/drpy_suggestions/drpy_suggestions.ts
=> 增加drpy涉及的变量，并且加入了多套起手式模板代码块

src/renderer/src/pages/Play.vue, src/renderer/src/utils/sniffer.ts
=> 修复嗅探传参可能存在的URL函数解析错误。新增getQuery方法

src/main/utils/pie.ts
=> 修复嗅探过程中多个窗口同时嗅探最后除了第一个窗口超时关闭之外其他窗口都不会关闭的问题

src/main/core/server/routes/file.ts, src/main/core/server/routes/test_index/index.js, src/renderer/src/pages/setting/base/components/DialogData.vue
1. 增加本地包生成式。index.js
2.一键导入支持解析直播多条配置的情况
=> 增加本地包生成式.优化直播批量导入

src/renderer/src/utils/drpy/drpy_suggestions/drpy_suggestions.ts
=> 增加rsa相关智能提示，优化$rule的lazy默认值

src/renderer/src/pages/setting/tool/EditSource.vue, src/renderer/src/utils/drpy/drpy_suggestions/drpy_object_inner.ts
=> 增加内部对象函数的智能提示

src/main/core/server/routes/lab/ad.ts, src/main/core/server/routes/lab/index.ts, src/renderer/src/api/lab.ts, src/renderer/src/pages/setting/tool/EditSource.vue, src/renderer/src/utils/common/film.ts, src/renderer/src/utils/drpy/drpy3.ts, src/renderer/src/utils/sniffer.ts, src/renderer/src/utils/tool.ts
=> 写源工具导出文件默认为服务目录。修复导出识别title匹配不准确的问题

src/main/core/ipc.ts, src/renderer/src/pages/setting/tool/EditSource.vue
=> 修复写源工具导出文件

src/main/core/ipc.ts, src/main/utils/pie.ts, src/renderer/src/utils/common/film.ts, src/renderer/src/utils/drpy/htmlParser.ts, src/renderer/src/utils/sniffer.ts
=> 昨天加的功能忘了pr

src/renderer/src/utils/drpy/template.ts
=> edit template.ts

src/main/core/server/routes/file.ts
=> 访问本地包生成式自动生成easybox可用的json

src/main/utils/pie.ts, src/renderer/src/utils/drpy/drpy3.ts, src/renderer/src/utils/drpy/drpyInject.ts, src/renderer/src/utils/drpy/drpy_suggestions/drpy_object_inner.ts, src/renderer/src/utils/drpy/drpy_suggestions/drpy_suggestions.ts
=> drpy接口升级。新增其他OCR支持。增加测试用例，增加智能提示

src/main/index.ts, src/renderer/src/pages/setting/tool/EditSource.vue, src/renderer/src/utils/drpy/drpyInject.ts
=> 默认增加accept解决部分网站获取源码的结果为unicode编码问题

src/renderer/src/utils/drpy/drpyInject.ts
=> 修复获取图片base64问题。

src/renderer/src/utils/drpy/drpy3.ts, src/renderer/src/utils/drpy/drpy_suggestions/drpy_suggestions.ts, src/renderer/src/utils/drpy/template.ts, src/renderer/src/utils/tool.ts
=> 增强辅助嗅探，增加reqCookie方法。增加智能提示

src/main/core/server/routes/cache.ts
=> cache接口返回200避免接口爆红

src/renderer/src/pages/setting/tool/EditSource.vue, src/renderer/src/utils/drpy/drpyInject.ts
=> 修复drpy3获取网页编码问题和写源工具获取源码某些网站不识别accept *的问题

src/renderer/src/utils/drpy/htmlParser.ts
=> 修复pd函数不支持data-开头属性自动拼接问题

src/renderer/src/utils/drpy/drpy3.ts, src/renderer/src/utils/drpy/drpy_suggestions/drpy_object_inner.ts, src/renderer/src/utils/drpy/drpy_suggestions/drpy_suggestions.ts
=> drpy接口优化。新增加密方式

package.json, src/main/utils/pie.ts
=> 修复嗅探过程中莫名其妙报错的问题

src/renderer/src/utils/drpy/drpy3.ts, src/renderer/src/utils/drpy/drpyInject.ts, src/renderer/src/utils/drpy/drpy_suggestions/drpy_suggestions.ts, src/renderer/src/utils/drpy/htmlParser.ts, src/renderer/src/utils/drpy/template.ts
=> drpy接口增加默认属性【类型】。修复drpy相关ts文件爆红问题

src/renderer/src/utils/drpy/drpy3.ts
=> drpy接口升级:规则的图片替换属性新增js写法支持

src/main/core/server/routes/lab/ad/core.ts
=> 修复for in的Bug

src/renderer/src/components/common-nav/index.vue, src/renderer/src/layouts/components/Header.vue, src/renderer/src/layouts/components/SystemControl.vue, src/renderer/src/locales/lang/en_US/pages/search.ts, src/renderer/src/locales/lang/zh_CN/pages/search.ts, src/renderer/src/pages/Film.vue, src/renderer/src/style/theme/theme.less
=> [optimization] Some details

src/renderer/src/utils/drpy/drpy3.ts, src/renderer/src/utils/drpy/drpyInject.ts
=> 修复drpy3 buildUrl表现异常问题

src/renderer/src/pages/Film.vue
=> 优化搜索逻辑问题，drpy/hipy系列非资源站禁用搜索无图自动请求二级的逻辑。提升搜索结果加载速度。优化搜索结果元素的文本显示。

src/renderer/src/pages/Film.vue, src/renderer/src/utils/drpy/drpy3.ts, src/renderer/src/utils/drpy/drpy_suggestions/drpy_suggestions.ts
=> drpy3接口升级，筛选支持fyclass。增加batchFetch智能提示

src/renderer/src/utils/drpy/drpy3.ts, src/renderer/src/utils/drpy/utils/jinja.js, src/renderer/src/utils/drpy/utils/json5.js
=> 更换drpy的jinja2引擎

src/main/core/server/routes/file.ts
=> 修复本地包生成式报错

src/renderer/src/components/common-nav/index.vue
=> [enhance] 打开侧边导航自动聚焦
